set magic
set mouse=a
set termguicolors

filetype plugin on

" Setting default tab width and use spaces for tabs
set tabstop=4
set shiftwidth=4 
set expandtab 
set smarttab
set autoindent
set smartindent

call plug#begin('~/.vim/plugged')

    Plug 'scrooloose/nerdtree'
    Plug 'vim-airline/vim-airline'
    Plug 'kaicataldo/material.vim'
    Plug 'mattn/emmet-vim'

call plug#end()

let g:airline#extensions#tabline#enabled = 1
let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['\.o$', '\.a$', '\.bin$', '\.swp$']

" Keyboard shortcuts
nnoremap <C-q> :bufdo bwipeout<CR>:q<CR>
nnoremap <C-b> :NERDTreeToggle<CR>

" Make *.asm files use nasm syntax by default
autocmd BufEnter *.asm setlocal syntax=nasm

" Make *.cjs and *.mjs be highlighted as javascript files
autocmd BufEnter *.cjs setlocal syntax=javascript
autocmd BufEnter *.mjs setlocal syntax=javascript

" Make html, js and css files use tab width 2
autocmd BufEnter *.html,*.css,*.pug,*.sass,*.scss,*.js,*.jsx,*.ts,*.tsx,*.json,*.cjs,*.mjs 
    \ setlocal tabstop=2 |
    \ setlocal shiftwidth=2

" Apply colorscheme
try
    colorscheme material
catch
endtry

